// ./src/boundary/connectorCategoriesAndTypes.ts
export const CONNECTOR_CATEGORIES = {
  WEBHOOKS: 'WEBHOOKS',
  STORAGE: 'STORAGE',
  MESSENGERS: 'MESSENGERS',
  CRM: 'CRM',
  PRODUCTIVITY: 'PRODUCTIVITY',
  EMAIL: 'EMAIL',
};

export const CONNECTOR_TYPES = {
  // Webhooks
  HTTP: 'HTTP',
  // Files FTP storage
  FTP: 'FTP',
  FTPS: 'FTPS',
  // Cloud
  AZURE_STORAGE_ACCOUNT_BLOB: 'AZURE_STORAGE_ACCOUNT_BLOB',
  AZURE_STORAGE_ACCOUNT_QUEUE: 'AZURE_STORAGE_ACCOUNT_QUEUE',
  AZURE_STORAGE_ACCOUNT_TABLE: 'AZURE_STORAGE_ACCOUNT_TABLE',
  AZURE_SERVICE_BUS: 'AZURE_SERVICE_BUS',
  AZURE_EVENT_GRID: 'AZURE_EVENT_GRID',
  AWS_S3: 'AWS_S3',
  AWS_SQS: 'AWS_SQS',
  AWS_SNS: 'AWS_SNS',
  AWS_EVENTBRIDGE: 'AWS_EVENTBRIDGE',
  AWS_DYNAMODB: 'AWS_DYNAMODB',
  GCP_STORAGE: 'GCP_STORAGE',
  GCP_PUBSUB: 'GCP_PUBSUB',
  GCP_FIRESTORE: 'GCP_FIRESTORE',
  // Messengers
  SLACK: 'SLACK',
  TELEGRAM: 'TELEGRAM',
  DISCORD: 'DISCORD',
  // CRM
  HUBSPOT: 'HUBSPOT',
  // Productivity
  GOOGLE_SHEETS: 'GOOGLE_SHEETS',
  NOTION: 'NOTION',
  AIRTABLE: 'AIRTABLE',
  TRELLO: 'TRELLO',
  GITHUB: 'GITHUB',
  MAILCHIMP: 'MAILCHIMP',
  CONVERTKIT: 'CONVERTKIT',
  // EMAIL
  SENDGRID: 'SENDGRID',
  SMTP: 'SMTP',
  AWS_SES: 'AWS_SES',
};
