export const vehicleMakes = [
  { id: 1, code: 'OTHER', name: 'Other' },
  { id: 2, code: 'ABARTH', name: 'Abarth' },
  { id: 3, code: 'ACURA', name: 'Acura' },
  { id: 4, code: 'AJP', name: 'AJP' },
  { id: 5, code: 'AJS', name: 'AJS' },
  { id: 6, code: 'ALFA_ROMEO', name: 'Alfa Romeo' },
  { id: 7, code: 'APRILIA', name: 'Aprilia' },
  { id: 8, code: 'ARCTIC_CAT', name: 'Arctic Cat' },
  { id: 9, code: 'ARGO', name: 'Argo' },
  { id: 10, code: 'ASCARI', name: 'Ascari' },
  { id: 11, code: 'ASTON_MARTIN', name: 'Aston Martin' },
  { id: 12, code: 'AUDI', name: 'Audi' },
  { id: 13, code: 'AUTOCAR', name: 'Autocar LLC.' },
  { id: 14, code: 'BAJAJ', name: 'Bajaj' },
  { id: 15, code: 'BENELLI', name: 'Benelli' },
  { id: 16, code: 'BENTLEY', name: 'Bentley' },
  { id: 17, code: 'BETA', name: 'Beta' },
  { id: 18, code: 'BIG_DOG', name: 'Big Dog' },
  { id: 19, code: 'BLUE_BIRD', name: 'Blue Bird' },
  { id: 20, code: 'BMW', name: 'BMW' },
  { id: 21, code: 'BOBCAT', name: 'Bobcat' },
  { id: 22, code: 'BRILLIANCE', name: 'Brilliance' },
  { id: 23, code: 'BUELL', name: 'Buell' },
  { id: 24, code: 'BUGATTI', name: 'Bugatti' },
  { id: 25, code: 'BUICK', name: 'Buick' },
  { id: 26, code: 'CADILLAC', name: 'Cadillac' },
  { id: 27, code: 'CAN_AM', name: 'Can-Am' },
  { id: 28, code: 'CAPACITY_OF_TEXAS', name: 'Capacity Of Texas' },
  { id: 29, code: 'CASE_IH', name: 'Case IH' },
  { id: 30, code: 'CATERPILLAR', name: 'Caterpillar' },
  { id: 31, code: 'CHERY', name: 'Chery' },
  { id: 32, code: 'CHEVROLET', name: 'Chevrolet' },
  { id: 33, code: 'CHRYSLER', name: 'Chrysler' },
  { id: 34, code: 'CITROEN', name: 'Citroën' },
  { id: 35, code: 'COBRA', name: 'Cobra' },
  { id: 36, code: 'CRANE_CARRIER', name: 'Crane Carrier' },
  { id: 37, code: 'CREATE_A_CUSTOM', name: 'Create A Custom' },
  { id: 38, code: 'CUB_CADET', name: 'Cub Cadet' },
  { id: 39, code: 'DACIA', name: 'Dacia' },
  { id: 40, code: 'DAELIM', name: 'Daelim' },
  { id: 41, code: 'DAEWOO', name: 'Daewoo' },
  { id: 42, code: 'DAIHATSU', name: 'Daihatsu' },
  { id: 43, code: 'DERBI', name: 'Derbi' },
  { id: 44, code: 'DIRECT_BIKES', name: 'Direct Bikes' },
  { id: 45, code: 'DODGE', name: 'Dodge' },
  { id: 46, code: 'DUCATI', name: 'Ducati' },
  { id: 47, code: 'ETON', name: 'E-TON' },
  { id: 48, code: 'EL_DORADO', name: 'El Dorado' },
  { id: 49, code: 'EMERGENCY_ONE', name: 'Emergency One' },
  { id: 50, code: 'EVOBUS', name: 'Evobus' },
  { id: 51, code: 'FERRARI', name: 'Ferrari' },
  { id: 52, code: 'FIAT', name: 'Fiat' },
  { id: 53, code: 'FORD', name: 'Ford' },
  { id: 54, code: 'FREIGHTLINER', name: 'Freightliner' },
  { id: 55, code: 'GAS_GAS', name: 'Gas Gas' },
  { id: 56, code: 'GEELY', name: 'Geely' },
  { id: 57, code: 'GENUINE', name: 'Genuine' },
  { id: 58, code: 'GILERA', name: 'Gilera' },
  { id: 59, code: 'GILLIG', name: 'Gillig' },
  { id: 60, code: 'GMC', name: 'GMC' },
  { id: 61, code: 'GREAT_WALL', name: 'Great Wall' },
  { id: 62, code: 'HARLEY_DAVIDSON', name: 'Harley-Davidson' },
  { id: 63, code: 'HENDRICKSON', name: 'Hendrickson' },
  { id: 64, code: 'HERO_HONDA', name: 'Hero Honda' },
  { id: 65, code: 'HINO', name: 'Hino' },
  { id: 66, code: 'HOLDEN', name: 'Holden' },
  { id: 67, code: 'HONDA', name: 'Honda' },
  { id: 68, code: 'HUMMER', name: 'Hummer' },
  { id: 69, code: 'HUONIAO', name: 'Huoniao' },
  { id: 70, code: 'HUSABERG', name: 'Husaberg' },
  { id: 71, code: 'HUSQVARNA', name: 'Husqvarna' },
  { id: 72, code: 'HYOSUNG', name: 'Hyosung' },
  { id: 73, code: 'HYUNDAI', name: 'Hyundai' },
  { id: 74, code: 'IC_CORPORATION', name: 'IC Corporation' },
  { id: 75, code: 'INDIAN', name: 'Indian' },
  { id: 76, code: 'INFINITI', name: 'Infiniti' },
  { id: 77, code: 'INTERNATIONAL', name: 'International' },
  { id: 78, code: 'ISUZU', name: 'Isuzu' },
  { id: 79, code: 'JAGUAR', name: 'Jaguar' },
  { id: 80, code: 'JAWA', name: 'Jawa' },
  { id: 81, code: 'JEEP', name: 'Jeep' },
  { id: 82, code: 'JOHN_DEERE', name: 'John Deere' },
  { id: 83, code: 'JONWAY', name: 'Jonway' },
  { id: 84, code: 'KALMAR', name: 'Kalmar' },
  { id: 85, code: 'KAWASAKI', name: 'Kawasaki' },
  { id: 86, code: 'KEEWAY', name: 'Keeway' },
  { id: 87, code: 'KENWORTH', name: 'Kenworth' },
  { id: 88, code: 'KIA', name: 'Kia' },
  { id: 89, code: 'KOVATCH', name: 'Kovatch' },
  { id: 90, code: 'KTM', name: 'KTM' },
  { id: 91, code: 'KUBOTA', name: 'Kubota' },
  { id: 92, code: 'KYMCO', name: 'KYMCO' },
  { id: 93, code: 'LADA', name: 'Lada (Лада)' },
  { id: 94, code: 'LAMBORGHINI', name: 'Lamborghini' },
  { id: 95, code: 'LANCE', name: 'Lance' },
  { id: 96, code: 'LANCIA', name: 'Lancia' },
  { id: 97, code: 'LAND_ROVER', name: 'Land Rover' },
  { id: 98, code: 'LEM', name: 'LEM' },
  { id: 99, code: 'LEXUS', name: 'Lexus' },
  { id: 100, code: 'LIFAN', name: 'Lifan' },
  { id: 101, code: 'LINCOLN', name: 'Lincoln' },
  { id: 102, code: 'LML', name: 'LML' },
  { id: 103, code: 'LONGJIA', name: 'Longjia' },
  { id: 104, code: 'LOTUS', name: 'Lotus' },
  { id: 105, code: 'LUXGEN', name: 'Luxgen' },
  { id: 106, code: 'MACK', name: 'Mack' },
  { id: 107, code: 'MAHINDRA', name: 'Mahindra' },
  { id: 108, code: 'MALAGUTI', name: 'Malaguti' },
  { id: 109, code: 'MASERATI', name: 'Maserati' },
  { id: 110, code: 'MAYBACH', name: 'Maybach' },
  { id: 111, code: 'MAZDA', name: 'Mazda' },
  { id: 112, code: 'MEGELLI', name: 'Megelli' },
  { id: 113, code: 'MERCEDES_BENZ', name: 'Mercedes-Benz' },
  { id: 114, code: 'MERCURY', name: 'Mercury' },
  { id: 115, code: 'MINI', name: 'Mini' },
  { id: 116, code: 'MITSUBISHI', name: 'Mitsubishi' },
  { id: 117, code: 'MODENAS', name: 'Modenas' },
  { id: 118, code: 'MONDIAL', name: 'Mondial' },
  { id: 119, code: 'MORGAN', name: 'Morgan' },
  { id: 120, code: 'MOTO_GUZZI', name: 'Moto Guzzi' },
  { id: 121, code: 'MOTO_MORINI', name: 'Moto Morini' },
  { id: 122, code: 'MOTORHISPANIA', name: 'Motorhispania' },
  { id: 123, code: 'MV_AGUSTA', name: 'MV Agusta' },
  { id: 124, code: 'NAZA', name: 'Naza' },
  { id: 125, code: 'NISSAN', name: 'Nissan' },
  { id: 126, code: 'NOVA_BUS', name: 'Nova Bus Corporation' },
  { id: 127, code: 'OPEL', name: 'Opel' },
  { id: 128, code: 'OSHKOSH', name: 'Oshkosh Motor Truck Co.' },
  { id: 129, code: 'PAGSTA', name: 'Pagsta' },
  { id: 130, code: 'PERODUA', name: 'Perodua' },
  { id: 131, code: 'PETERBILT', name: 'Peterbilt' },
  { id: 132, code: 'PEUGEOT', name: 'Peugeot' },
  { id: 133, code: 'PGO', name: 'PGO' },
  { id: 134, code: 'PIAGGIO', name: 'Piaggio' },
  { id: 135, code: 'PIERCE_MFG', name: 'Pierce Mfg. Inc.' },
  { id: 136, code: 'PIONEER', name: 'Pioneer' },
  { id: 137, code: 'POLARIS', name: 'Polaris' },
  { id: 138, code: 'POLINI', name: 'Polini' },
  { id: 139, code: 'PONTIAC', name: 'Pontiac' },
  { id: 140, code: 'PORSCHE', name: 'Porsche' },
  { id: 141, code: 'PREVOST', name: 'Prevost' },
  { id: 142, code: 'PROTON', name: 'Proton' },
  { id: 143, code: 'PULSE', name: 'Pulse' },
  { id: 144, code: 'RAM', name: 'Ram' },
  { id: 145, code: 'RENAULT', name: 'Renault' },
  { id: 146, code: 'REWACO', name: 'Rewaco Trikes' },
  { id: 147, code: 'RIEJU', name: 'Rieju' },
  { id: 148, code: 'ROADMASTER_RAIL', name: 'Roadmaster Rail' },
  { id: 149, code: 'ROLLS_ROYCE', name: 'Rolls-Royce' },
  { id: 150, code: 'ROYAL_ENFIELD', name: 'Royal Enfield' },
  { id: 151, code: 'SAAB', name: 'Saab' },
  { id: 152, code: 'SACHS', name: 'Sachs' },
  { id: 153, code: 'SAMSUNG', name: 'Samsung' },
  { id: 154, code: 'SATURN', name: 'Saturn' },
  { id: 155, code: 'SCION', name: 'Scion' },
  { id: 156, code: 'SEA_DOO', name: 'Sea-Doo' },
  { id: 157, code: 'SEAT', name: 'Seat' },
  { id: 158, code: 'SINNIS', name: 'Sinnis' },
  { id: 159, code: 'SKI_DOO', name: 'Ski-Doo' },
  { id: 160, code: 'SKODA', name: 'Škoda' },
  { id: 161, code: 'SKYTEAM', name: 'Skyteam' },
  { id: 162, code: 'SMART', name: 'Smart' },
  { id: 163, code: 'SPARTAN_MOTORS', name: 'Spartan Motors' },
  { id: 164, code: 'SSANGYONG', name: 'SsangYong' },
  { id: 165, code: 'SUBARU', name: 'Subaru' },
  { id: 166, code: 'SUZUKI', name: 'Suzuki' },
  { id: 167, code: 'SYM', name: 'SYM' },
  { id: 168, code: 'SYM_SR_150', name: 'SYM SR 150' },
  { id: 169, code: 'TATA', name: 'Tata' },
  { id: 170, code: 'TEREX', name: 'Terex / Terex Advance' },
  { id: 171, code: 'TESLA', name: 'Tesla' },
  { id: 172, code: 'THOMAS', name: 'Thomas' },
  { id: 173, code: 'TM', name: 'TM' },
  { id: 174, code: 'TOYOTA', name: 'Toyota' },
  { id: 175, code: 'TRIUMPH', name: 'Triumph' },
  { id: 176, code: 'TVS_MOTORS', name: 'TVS Motors' },
  { id: 177, code: 'URAL', name: 'Ural (Урал)' },
  { id: 178, code: 'VAN_HOOL', name: 'Van Hool' },
  { id: 179, code: 'VAUXHALL', name: 'Vauxhall' },
  { id: 180, code: 'VESPA', name: 'Vespa' },
  { id: 181, code: 'VICTORY', name: 'Victory' },
  { id: 182, code: 'VOLKSWAGEN', name: 'Volkswagen' },
  { id: 183, code: 'VOLVO', name: 'Volvo' },
  { id: 184, code: 'WESTERN_STAR', name: 'Western Star' },
  { id: 185, code: 'XINGYUE', name: 'Xingyue' },
  { id: 186, code: 'YAMAHA', name: 'Yamaha' },
  { id: 187, code: 'ZONGSHEN', name: 'Zongshen' },
  // Russian/CIS manufacturers
  { id: 188, code: 'MAZ', name: 'MAZ (МАЗ)' },
  { id: 189, code: 'MAZ_MAN', name: 'MAZ-MAN (МАЗ-МАН)' },
  { id: 190, code: 'KAMAZ', name: 'Kamaz (Камаз)' },
  { id: 191, code: 'GAZ', name: 'GAZ (ГАЗ)' },
  { id: 192, code: 'ZIL', name: 'ZIL (ЗИЛ)' },
  { id: 193, code: 'UAZ', name: 'UAZ (УАЗ)' },
  // ==========================================
  // NEW MAKES (IDs starting from 200)
  // ==========================================
  // Electric/Modern brands
  { id: 200, code: 'BYD', name: 'BYD' },
  { id: 201, code: 'RIVIAN', name: 'Rivian' },
  { id: 202, code: 'LUCID', name: 'Lucid' },
  { id: 203, code: 'POLESTAR', name: 'Polestar' },
  { id: 204, code: 'NIO', name: 'NIO' },
  { id: 205, code: 'XPENG', name: 'XPeng' },
  { id: 206, code: 'LI_AUTO', name: 'Li Auto' },
  { id: 207, code: 'VINFAST', name: 'VinFast' },
  { id: 208, code: 'GENESIS', name: 'Genesis' },
  { id: 209, code: 'CUPRA', name: 'Cupra' },
  { id: 210, code: 'DS', name: 'DS Automobiles' },
  { id: 211, code: 'ALPINE', name: 'Alpine' },
  { id: 212, code: 'FISKER', name: 'Fisker' },
  { id: 213, code: 'CANOO', name: 'Canoo' },
  { id: 214, code: 'LORDSTOWN', name: 'Lordstown' },
  { id: 215, code: 'FARADAY_FUTURE', name: 'Faraday Future' },
  // Chinese brands
  { id: 216, code: 'HAVAL', name: 'Haval' },
  { id: 217, code: 'WULING', name: 'Wuling' },
  { id: 218, code: 'CHANGAN', name: 'Changan' },
  { id: 219, code: 'DONGFENG', name: 'Dongfeng' },
  { id: 220, code: 'FAW', name: 'FAW' },
  { id: 221, code: 'JAC', name: 'JAC' },
  { id: 222, code: 'BAIC', name: 'BAIC' },
  { id: 223, code: 'ZOTYE', name: 'Zotye' },
  { id: 224, code: 'GAC', name: 'GAC' },
  { id: 225, code: 'FOTON', name: 'Foton' },
  { id: 226, code: 'SAIC', name: 'SAIC' },
  { id: 227, code: 'MG', name: 'MG' },
  { id: 228, code: 'LYNK_CO', name: 'Lynk & Co' },
  { id: 229, code: 'ZEEKR', name: 'Zeekr' },
  { id: 230, code: 'ORA', name: 'ORA' },
  { id: 231, code: 'TANK', name: 'Tank' },
  { id: 232, code: 'WUYAN', name: 'Wuyan' },
  // Supercars/Luxury
  { id: 233, code: 'MCLAREN', name: 'McLaren' },
  { id: 234, code: 'KOENIGSEGG', name: 'Koenigsegg' },
  { id: 235, code: 'PAGANI', name: 'Pagani' },
  { id: 236, code: 'RIMAC', name: 'Rimac' },
  { id: 237, code: 'SPYKER', name: 'Spyker' },
  { id: 238, code: 'NOBLE', name: 'Noble' },
  { id: 239, code: 'ZENVO', name: 'Zenvo' },
  { id: 240, code: 'ARIEL', name: 'Ariel' },
  { id: 241, code: 'BAC', name: 'BAC' },
  { id: 242, code: 'RADICAL', name: 'Radical' },
  { id: 243, code: 'GINETTA', name: 'Ginetta' },
  { id: 244, code: 'TVR', name: 'TVR' },
  { id: 245, code: 'BRISTOL', name: 'Bristol' },
  { id: 246, code: 'WIESMANN', name: 'Wiesmann' },
  { id: 247, code: 'GUMPERT', name: 'Gumpert' },
  { id: 248, code: 'SSC', name: 'SSC' },
  { id: 249, code: 'HENNESSEY', name: 'Hennessey' },
  { id: 250, code: 'SALEEN', name: 'Saleen' },
  // Trucks/Commercial
  { id: 251, code: 'SCANIA', name: 'Scania' },
  { id: 252, code: 'MAN', name: 'MAN' },
  { id: 253, code: 'DAF', name: 'DAF' },
  { id: 254, code: 'IVECO', name: 'Iveco' },
  { id: 255, code: 'NAVISTAR', name: 'Navistar' },
  { id: 256, code: 'UD_TRUCKS', name: 'UD Trucks' },
  { id: 257, code: 'FUSO', name: 'Fuso' },
  // Motorcycles (additional)
  { id: 258, code: 'ZERO', name: 'Zero Motorcycles' },
  { id: 259, code: 'ENERGICA', name: 'Energica' },
  { id: 260, code: 'LIVEWIRE', name: 'LiveWire' },
  { id: 261, code: 'SUR_RON', name: 'Sur-Ron' },
  { id: 262, code: 'CFMoto', name: 'CFMoto' },
  { id: 263, code: 'SWM', name: 'SWM' },
  { id: 264, code: 'FANTIC', name: 'Fantic' },
  { id: 265, code: 'SHERCO', name: 'Sherco' },
  { id: 266, code: 'TM_RACING', name: 'TM Racing' },
  { id: 267, code: 'BIMOTA', name: 'Bimota' },
  { id: 268, code: 'NORTON', name: 'Norton' },
  { id: 269, code: 'BSA', name: 'BSA' },
  // Russian/CIS (additional)
  { id: 270, code: 'MOSKVITCH', name: 'Moskvitch (Москвич)' },
  { id: 271, code: 'VOLGA', name: 'Volga (Волга)' },
  { id: 272, code: 'IZH', name: 'IZH (ИЖ)' },
  { id: 273, code: 'AZLK', name: 'AZLK (АЗЛК)' },
  { id: 274, code: 'BELAZ', name: 'BelAZ (БелАЗ)' },
  { id: 275, code: 'PAZ', name: 'PAZ (ПАЗ)' },
  { id: 276, code: 'KAVZ', name: 'KAVZ (КАВЗ)' },
  { id: 277, code: 'LIAZ', name: 'LiAZ (ЛиАЗ)' },
  { id: 278, code: 'NEFAZ', name: 'NefAZ (НефАЗ)' },
  // Other notable brands
  { id: 279, code: 'DATSUN', name: 'Datsun' },
  { id: 280, code: 'OLDSMOBILE', name: 'Oldsmobile' },
  { id: 281, code: 'PLYMOUTH', name: 'Plymouth' },
  { id: 282, code: 'AMC', name: 'AMC' },
  { id: 283, code: 'STUDEBAKER', name: 'Studebaker' },
  { id: 284, code: 'PACKARD', name: 'Packard' },
  { id: 285, code: 'NASH', name: 'Nash' },
  { id: 286, code: 'HUDSON', name: 'Hudson' },
  { id: 287, code: 'DELOREAN', name: 'DeLorean' },
  { id: 288, code: 'EAGLE', name: 'Eagle' },
  { id: 289, code: 'GEO', name: 'Geo' },
  { id: 290, code: 'ISUZU_TRUCK', name: 'Isuzu Commercial' },
  { id: 291, code: 'WORKHORSE', name: 'Workhorse' },
  { id: 292, code: 'BOLLINGER', name: 'Bollinger' },
  { id: 293, code: 'LORDSTOWN_MOTORS', name: 'Lordstown Motors' },
  { id: 294, code: 'NIKOLA', name: 'Nikola' },
  { id: 295, code: 'HYZON', name: 'Hyzon' },
  { id: 296, code: 'AVIA', name: 'Avia' },
  { id: 297, code: 'TATRA', name: 'Tatra' },
  { id: 298, code: 'IKARUS', name: 'Ikarus' },
  { id: 299, code: 'NEOPLAN', name: 'Neoplan' },
  { id: 300, code: 'SETRA', name: 'Setra' },
];

// Type exports
export type VehicleMake = (typeof vehicleMakes)[number];
export type VehicleMakeCode = VehicleMake['code'];

// Helper to get make by id
export const getVehicleMakeById = (id: number): VehicleMake | undefined => {
  return vehicleMakes.find((make) => make.id === id);
};

// Helper to get make by code
export const getVehicleMakeByCode = (code: string): VehicleMake | undefined => {
  return vehicleMakes.find((make) => make.code === code);
};

// Helper to search makes by name (case-insensitive)
export const searchVehicleMakes = (query: string): VehicleMake[] => {
  const lowerQuery = query.toLowerCase();
  return vehicleMakes.filter((make) => make.name.toLowerCase().includes(lowerQuery));
};